/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DatasourcesRouteImport } from './routes/datasources'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasourceIdRouteImport } from './routes/datasource.$id'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardIdSheetSheetIdRouteImport } from './routes/dashboard.$id/sheet.$sheetId'
import { Route as AnalysisIdSheetSheetIdRouteImport } from './routes/analysis.$id/sheet.$sheetId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesRoute = DatasourcesRouteImport.update({
  id: '/datasources',
  path: '/datasources',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourceIdRoute = DatasourceIdRouteImport.update({
  id: '/datasource/$id',
  path: '/datasource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdSheetSheetIdRoute = DashboardIdSheetSheetIdRouteImport.update({
  id: '/sheet/$sheetId',
  path: '/sheet/$sheetId',
  getParentRoute: () => DashboardIdRoute,
} as any)
const AnalysisIdSheetSheetIdRoute = AnalysisIdSheetSheetIdRouteImport.update({
  id: '/sheet/$sheetId',
  path: '/sheet/$sheetId',
  getParentRoute: () => AnalysisIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboards': typeof DashboardsRoute
  '/datasources': typeof DatasourcesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/datasource/$id': typeof DatasourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/analysis/$id/sheet/$sheetId': typeof AnalysisIdSheetSheetIdRoute
  '/dashboard/$id/sheet/$sheetId': typeof DashboardIdSheetSheetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboards': typeof DashboardsRoute
  '/datasources': typeof DatasourcesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/datasource/$id': typeof DatasourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/analysis/$id/sheet/$sheetId': typeof AnalysisIdSheetSheetIdRoute
  '/dashboard/$id/sheet/$sheetId': typeof DashboardIdSheetSheetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/dashboards': typeof DashboardsRoute
  '/datasources': typeof DatasourcesRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/datasource/$id': typeof DatasourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/analysis/$id/sheet/$sheetId': typeof AnalysisIdSheetSheetIdRoute
  '/dashboard/$id/sheet/$sheetId': typeof DashboardIdSheetSheetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/dashboards'
    | '/datasources'
    | '/signin'
    | '/signup'
    | '/analysis/$id'
    | '/dashboard/$id'
    | '/datasource/$id'
    | '/api/auth/$'
    | '/analysis/$id/sheet/$sheetId'
    | '/dashboard/$id/sheet/$sheetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/dashboards'
    | '/datasources'
    | '/signin'
    | '/signup'
    | '/analysis/$id'
    | '/dashboard/$id'
    | '/datasource/$id'
    | '/api/auth/$'
    | '/analysis/$id/sheet/$sheetId'
    | '/dashboard/$id/sheet/$sheetId'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/dashboards'
    | '/datasources'
    | '/signin'
    | '/signup'
    | '/analysis/$id'
    | '/dashboard/$id'
    | '/datasource/$id'
    | '/api/auth/$'
    | '/analysis/$id/sheet/$sheetId'
    | '/dashboard/$id/sheet/$sheetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  DashboardsRoute: typeof DashboardsRoute
  DatasourcesRoute: typeof DatasourcesRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AnalysisIdRoute: typeof AnalysisIdRouteWithChildren
  DashboardIdRoute: typeof DashboardIdRouteWithChildren
  DatasourceIdRoute: typeof DatasourceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources': {
      id: '/datasources'
      path: '/datasources'
      fullPath: '/datasources'
      preLoaderRoute: typeof DatasourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasource/$id': {
      id: '/datasource/$id'
      path: '/datasource/$id'
      fullPath: '/datasource/$id'
      preLoaderRoute: typeof DatasourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/sheet/$sheetId': {
      id: '/dashboard/$id/sheet/$sheetId'
      path: '/sheet/$sheetId'
      fullPath: '/dashboard/$id/sheet/$sheetId'
      preLoaderRoute: typeof DashboardIdSheetSheetIdRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/analysis/$id/sheet/$sheetId': {
      id: '/analysis/$id/sheet/$sheetId'
      path: '/sheet/$sheetId'
      fullPath: '/analysis/$id/sheet/$sheetId'
      preLoaderRoute: typeof AnalysisIdSheetSheetIdRouteImport
      parentRoute: typeof AnalysisIdRoute
    }
  }
}

interface AnalysisIdRouteChildren {
  AnalysisIdSheetSheetIdRoute: typeof AnalysisIdSheetSheetIdRoute
}

const AnalysisIdRouteChildren: AnalysisIdRouteChildren = {
  AnalysisIdSheetSheetIdRoute: AnalysisIdSheetSheetIdRoute,
}

const AnalysisIdRouteWithChildren = AnalysisIdRoute._addFileChildren(
  AnalysisIdRouteChildren,
)

interface DashboardIdRouteChildren {
  DashboardIdSheetSheetIdRoute: typeof DashboardIdSheetSheetIdRoute
}

const DashboardIdRouteChildren: DashboardIdRouteChildren = {
  DashboardIdSheetSheetIdRoute: DashboardIdSheetSheetIdRoute,
}

const DashboardIdRouteWithChildren = DashboardIdRoute._addFileChildren(
  DashboardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  DashboardsRoute: DashboardsRoute,
  DatasourcesRoute: DatasourcesRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AnalysisIdRoute: AnalysisIdRouteWithChildren,
  DashboardIdRoute: DashboardIdRouteWithChildren,
  DatasourceIdRoute: DatasourceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
